services:
  redis:
    image: redis:alpine
    container_name: order_service_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: