# Generated by Django 5.1.7 on 2025-06-08 17:24

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_contact_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Основное изображение товара', null=True, upload_to='products/', verbose_name='Изображение товара'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Изображение профиля пользователя', null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
